language: cpp

dist: xenial

addons:
  apt:
    packages:
    - libgtest-dev
    - libhdf4-dev

compiler:
- clang
- gcc

install:
- mkdir gtest
- cd gtest
- cmake /usr/src/gtest
- make --jobs=$(nproc)
- cd ..

script:
# https://cmake.org/cmake/help/v3.12/module/FindGTest.html
- GTEST_ROOT="$PWD/gtest"
  cmake
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  -DCMAKE_CXX_CLANG_TIDY='clang-tidy;-p=compile_commands.json'
  .
- make --jobs=$(nproc)
- tests/hdf4cpp-tests
